# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
from os import getenv


EDITOR = getenv('VISUAL')
TERMINAL = getenv('TERMINAL')
QB_CONFIG = getenv('QUTEBROWSER_CFG_FILE')
VIDEO_PATH = getenv('VIDEOS') + '/'
DOWNLOADS_PATH = getenv('DOWNLOADS') + '/'


# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable pdf.js.
# Type: Bool
config.set('content.pdfjs', True)

# Directory to save downloads to. If unset, a sensible OS-specific
# default is used.
# Type: Directory
c.downloads.location.directory = DOWNLOADS_PATH

config.source('themes/onedark.py')

c.tabs.padding = {'bottom': 7, 'left': 7, 'right': 7, 'top': 7}
c.tabs.indicator.width = 0

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '12pt Cascadia Code'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 12pt Cascadia Code'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '12pt Cascadia Code'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '12pt Cascadia Code'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 12pt Cascadia Code'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '12pt Cascadia Code'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '12pt Cascadia Code'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '12pt Cascadia Code'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '12pt Cascadia Code'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '12pt Cascadia Code'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '12pt Cascadia Code'

# Font used in the tab bar.
# Type: QtFont
#c.fonts.tabs = '12pt Cascadia Code'

c.zoom.default = '110%'

# Bindings for normal mode
config.bind('<return>', 'follow-selected')
config.bind('B', ':buffer')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('D', 'hint links spawn yt-dlp --all-subs --output ' + VIDEO_PATH + ' {hint-url}')
config.bind('e', 'open-editor')
config.bind('E', f'spawn {TERMINAL} -e {EDITOR} {QB_CONFIG}')

# Editor (and arguments) to use for the `open-editor` command. The
# following placeholders are defined: * `{file}`: Filename of the file
# to be edited. * `{line}`: Line in which the caret is found in the
# text. * `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = [
    f'{TERMINAL}',
    '-e',
    f'{EDITOR}',
    '-f',
    '{file}',
    '-c',
    'normal {line}G{column0}l'
]

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'y': 'https://www.youtube.com/results?search_query={}',
    'g': 'https://www.google.com.ar/search?q={}',
    'gh': 'https://github.com/search?q={}',
    't': 'https://translate.google.com/#view=home&op=translate&sl=en&tl=pt&text={}'
}

c.colors.webpage.darkmode.enabled = True
