---

- name: Sync package database
  become: true
  become_user: root
  xbps:
    update_cache: yes

# TODO: put the packages into a global variable
- name: Install common packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - ctags
      - docker
      - docker-compose
      - firefox
      - fzf
      - gimp
      - git
      - htop
      - i3blocks
      - lightdm
      - lightdm-gtk3-greeter
      - mpv
      - neofetch
      - qutebrowser
      - ranger
      - rofi
      - shellcheck
      - strace
      - tmux
      - vim
      - zathura

- name: Install void packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - base-devel
      - betterlockscreen
      - font-awesome
      - i3-gaps
      - man-pages-devel
      - man-pages-posix
      - neovim
      - newsboat
      - nitrogen
#      - nm-applet
      - python3-pip
      - recordmydesktop
      - scrot
      - telegram-desktop
      - texlive2020-bin
      - the_silver_searcher
#      - unrar
      - volumeicon
      - xbacklight
      - xclipboard
      - xorg-fonts
      - xorg-minimal
      - w3m-img
      - zathura-pdf-mupdf

...
