command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# Date Time
#
[time]
label=
command=date '+%a %d, %b %H:%M'
interval=5
separator=true
color=#e9d5c6

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
interval=30
separator=true
command=$SCRIPTS/i3blocks/battery
color=#e9d5c6
