#!/bin/sh

filename="%Y-%m-%d-%T_scrot.png"
cmd_list="xclip -selection clipboard -t image/png -i $filename && \
  mv $filename $IMAGES/$filename"

scrot -s "$filename" -e "$cmd_list" && notify-send 'screen captured'
