#!/bin/sh

# TODO: look for a better way to do this

workspaces=""
for i in $(ls ~/.tmuxp); do
  workspaces=" $i\n$workspaces"
done

selected=$( \
  echo "$workspaces" | \
  rofi -dmenu -p "Select the project" -width 22 | \
  cut -f2 -d' ' | \
  cut -f1 -d'.' \
)
[ -z "$selected" ] || "$TERMINAL" -e "tmuxp load $selected"
