#!/bin/sh

workspaces=$(ls ~/.tmuxp | cut -f1 -d'.')
selected_ws=$( \
  echo "$workspaces" | \
  rofi -dmenu -p "Select the project" -width 22
)
[ -z "$selected_ws" ] || "$TERMINAL" -e tmuxp load $selected_ws
