# pkg manager aliases
alias pkg-install="sudo apt install"
alias pkg-remove="sudo apt remove"
alias pkg-upgrade="sudo apt upgrade"
alias pkg-update="sudo apt update"
alias pkg-search="apt search"
alias pkg-list="dpkg --get-selections"
alias pkg-show="apt show"

# git aliases
alias gs="git status"
alias gc="git commit"
alias gl="git log"
alias ga="git add"
alias gr="git rebase -i"
alias gm="git merge"
alias gb="git branch"
alias gf="git fetch --all"
alias gca="git commit --amend"
alias gpl="git pull origin"
alias gps="git push origin"
alias gch="git checkout"
alias gcp="git cherry-pick"
alias gcl="git clone"
alias gdf="git diff"

# others
alias v="vim"
alias nv="nvim"
alias xcp="xclip -selection clipboard"
alias cp="cp -v"
alias mv="mv -v"
alias dd="dd status=progress"
