#!/bin/sh

cmd_out=$(acpi -b | tr -d ',')
percent=$(echo "$cmd_out" | awk '{print $4}' | tr -d '%')
status_str=$(echo "$cmd_out" | awk '{print $3}')

case $status_str in
  "Charging") status=" +" ;;
  "Discharging") status=" -" ;;
  *) status="" ;;
esac

if [ "$percent" -gt 90 ]; then # 91 - 100
  icon=
elif [ "$percent" -lt 91 ] && [ "$percent" -gt 74 ]; then # 75 - 90
  icon=
elif [ "$percent" -lt 75 ] && [ "$percent" -gt 49 ]; then # 50 - 74
  icon=
elif [ "$percent" -lt 50 ] && [ "$percent" -gt 5 ]; then # 6 - 49
  icon=
else
  icon=  # 0 - 5
fi

echo "${icon}" "${status}" "${percent}"%
